# Introduction

In this notebook we first cover conditional (```if```) statements and ```for``` /```while``` statements, before discussing how to loop over lists and dictionaries. At the end we look at defining and using, functions in Python.

# General Features of Control Flow Statements

In python the flow of code through a program can be controlled by a variety of different types of statements. In this notebook we consider ```if```, ```for```  and ```while``` statements, but you may also come across ```try``` statements (which specify exception handlers and/or cleanup code) or ```with``` statements (which allows execution of initialization and finalization code, prior to running a block of code).

All control flow statements share a common form. In pseudo code this is 

```
main body of code 

control flow (if/for/while/try/with) statement : 
    statement 
    statement
    
return to main body of code 
```
Note, the most important inclusion of a colon at the end of the header statement, followed by the indented lines which signify the block of code to be run (or not run) as a response to the header.

# Conditional (if) statements

In its simplest (pseudo) code form, an if statement in python looks like this:

```if condition:
    statement
    statement ```

The conditional statement must evaluate to a boolean (```True/False```)  but otherwise there are few constraints, examples include:

In [1]:
BMI=9

if BMI > 25.0:
    print('This person is overweight')
elif BMI<10:
  print('Person very sick')
else:
  print('This person is NOT  overweight')

BSA = 5
if BSA > 4:
    print('This person is huge')
elif BSA <2:
    print('This person is tiny')
else:
  print('This person alright')



if BMI >= 20 and BMI<26:

  print('This person has a good BMI')

if 20<=BMI<25:
    print('This person has a good BMI')


# or 

name='John'

if name=='John':
    print("This person's name is John ")


EF=45
import numpy as np
a=np.array([56, 57, 72, 25])
for i, EF in enumerate(a):

  if i>0:
    if EF > 55 :
      print('This person has an EF of {}%, which means he has a good heart function' .format(EF))

    elif EF < 35:
      print('This person has an EF of {}%, which means he has a severe systolic dysfunction' .format(EF))
    

    else:
      print('This person has an EF of {}%, which means he has a moderate systolic dysfunction' .format(EF))

Person very sick
This person is huge
This person's name is John
This person has an EF of 57%, which means he has a good heart function
This person has an EF of 72%, which means he has a good heart function
This person has an EF of 25%, which means he has a severe systolic dysfunction

In [ ]:
import numpy as np
anarray = np.arange(5,56,5)
print(anarray)

arc=np.arange(3,10105,50)
print(arc)

[ 5 10 15 20 25 30 35 40 45 50 55]
[    3    53   103   153   203   253   303   353   403   453   503   553
   603   653   703   753   803   853   903   953  1003  1053  1103  1153
  1203  1253  1303  1353  1403  1453  1503  1553  1603  1653  1703  1753
  1803  1853  1903  1953  2003  2053  2103  2153  2203  2253  2303  2353
  2403  2453  2503  2553  2603  2653  2703  2753  2803  2853  2903  2953
  3003  3053  3103  3153  3203  3253  3303  3353  3403  3453  3503  3553
  3603  3653  3703  3753  3803  3853  3903  3953  4003  4053  4103  4153
  4203  4253  4303  4353  4403  4453  4503  4553  4603  4653  4703  4753
  4803  4853  4903  4953  5003  5053  5103  5153  5203  5253  5303  5353
  5403  5453  5503  5553  5603  5653  5703  5753  5803  5853  5903  5953
  6003  6053  6103  6153  6203  6253  6303  6353  6403  6453  6503  6553
  6603  6653  6703  6753  6803  6853  6903  6953  7003  7053  7103  7153
  7203  7253  7303  7353  7403  7453  7503  7553  7603  7653  7703  7753
  7803  7853  7903  7953  8003  8053  8103  8153  8203  8253  8303  8353
  8403  8453  8503  8553  8603  8653  8703  8753  8803  8853  8903  8953
  9003  9053  9103  9153  9203  9253  9303  9353  9403  9453  9503  9553
  9603  9653  9703  9753  9803  9853  9903  9953 10003 10053 10103]

In [ ]:
import numpy as np
asset = np.array((5,67,3,29,100,75,63,85,91,9,21,34,7,7,95,145,34,23,19,38,73,52,67,90))
asset = asset.reshape(8,3)
print(asset)
asset2 = asset.reshape(2,2,6)
print(asset2)
asset3 = asset.reshape (2,6,2)
print(asset3)
even_asset = (asset % 2 ==0)
print(even_asset)
np.zeros(5)
np.zeros((5,4))+6

[[  5  67   3]
 [ 29 100  75]
 [ 63  85  91]
 [  9  21  34]
 [  7   7  95]
 [145  34  23]
 [ 19  38  73]
 [ 52  67  90]]
[[[  5  67   3  29 100  75]
  [ 63  85  91   9  21  34]]

 [[  7   7  95 145  34  23]
  [ 19  38  73  52  67  90]]]
[[[  5  67]
  [  3  29]
  [100  75]
  [ 63  85]
  [ 91   9]
  [ 21  34]]

 [[  7   7]
  [ 95 145]
  [ 34  23]
  [ 19  38]
  [ 73  52]
  [ 67  90]]]
[[False False False]
 [False  True False]
 [False False False]
 [False False  True]
 [False False False]
 [False  True False]
 [False  True False]
 [ True False  True]]

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
def EFdefinition(EF):
    if EF > 55 :
      print('This persone has an EF of {:.2f}%, which means he has a good heart function' .format(EF))

    elif EF < 35:
      print('This persone has an EF of {:.2f}%, which means he has a severe systolic dysfunction' .format(EF))

    else:
      print('This persone has an EF of {:.2f}%, which means he has a moderate systolic dysfunction' .format(EF))


import numpy as np
a=np.array([56, 57, 72, 25])
for i, EF in enumerate(a):
  EFdefinition(EF)


def EFcompute(EDV, ESV):
  EF = (EDV-ESV)/EDV*100
  return EF

print(EFcompute(160,100))



b=np.array([[180, 140], [190, 145], [200, 150], [205, 155], [210,160]]) #b=EDV,ESV
for EDV,ESV in b:
  print("EDV = {}, ESV = {}, EF = {}". format(EDV,ESV, EF))
  EFdefinition(EF)


def EFcompute(EDV,ESV):
  return (EDV-ESV)/EDV*100

print(EFcompute(160,100))



b=np.array([[180, 140], [190, 145], [200, 150], [205, 155], [210,160]]) #b=EDV,ESV
for EDV,ESV in b:
  print("EDV = {}, ESV = {}, EF = {:.2f}". format(EDV,ESV, EFcompute(EDV,ESV)))
  EFdefinition(EFcompute(EDV,ESV))

This persone has an EF of 56.00%, which means he has a good heart function
This persone has an EF of 57.00%, which means he has a good heart function
This persone has an EF of 72.00%, which means he has a good heart function
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
37.5
EDV = 180, ESV = 140, EF = 25
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
EDV = 190, ESV = 145, EF = 25
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
EDV = 200, ESV = 150, EF = 25
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
EDV = 205, ESV = 155, EF = 25
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
EDV = 210, ESV = 160, EF = 25
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
37.5
EDV = 180, ESV = 140, EF = 22.22
This persone has an EF of 22.22%, which means he has a severe systolic dysfunction
EDV = 190, ESV = 145, EF = 23.68
This persone has an EF of 23.68%, which means he has a severe systolic dysfunction
EDV = 200, ESV = 150, EF = 25.00
This persone has an EF of 25.00%, which means he has a severe systolic dysfunction
EDV = 205, ESV = 155, EF = 24.39
This persone has an EF of 24.39%, which means he has a severe systolic dysfunction
EDV = 210, ESV = 160, EF = 23.81
This persone has an EF of 23.81%, which means he has a severe systolic dysfunction

All forms of conditional statement (described in 2.2. Introduction to Types) may be used, including use or ```is/and/or``` statements e.g.

In [ ]:
a=10
b=12

if a< 15 and b > 10:
    print('run the following block of code')

run the following block of code

The "in" operator can also be used to check if a specified object exists within an iterable object container, such as a list:

In [ ]:
name = "John"
if name in ["John", "Dave"]:
    print("The person's name is either John or Dave.")

The person's name is either John or Dave.

Series of if statements can be combined within if else statements i.e.

In [ ]:
BMI=20

if BMI <= 18.5: # >= greater than or equal to
    print('This person is underweight')
elif BMI > 18.5 and BMI <=25.0:
    print('This person has normal weight')
elif BMI > 25.0 and BMI <=30.0 :
    print('This person is overweight')
else:
    print('This person is obese')

This person has normal weight

HINT - try changing the BMI and exploring the response

# For statements

For loops iterate over a given sequence, for example as given by a list:

In [ ]:
mylist=[10,20,30,40,50]
print(mylist)

for item in mylist:
    print(item)

for i, item in enumerate( mylist):
    print(i)
    print(item)

newlist=["blue", "orange", "red", "pink", "green"]
for i, item in enumerate(newlist):
    print(i, item)

[10, 20, 30, 40, 50]
10
20
30
40
50
0
10
1
20
2
30
3
40
4
50
0 blue
1 orange
2 red
3 pink
4 green

For numeric ranges, python the provides function ```range(start,end,increment)``` which provides an inline definition e.g.

In [ ]:
item =4
print(item in range(10))

for item in range(10):
    print(item)

True
0
1
2
3
4
5
6
7
8
9

**HINT, try changing the range and adding different increments, start and end points)**

It is possible to have for loops nested within each other, see an example below

In [ ]:
#the first code block
myfirstlist=[10,20,30,40]
mysecondlist=[1,2,3,4,5]

for tens in myfirstlist:
    #the second code block (a for loop over a list of integers)
    for units in mysecondlist:
        #the third code block (a for loop over a second list of integers)
        new_number=tens+units
        print('Output of third code block; The new number is',new_number)
print(tens)

Output of third code block; The new number is 11
Output of third code block; The new number is 12
Output of third code block; The new number is 13
Output of third code block; The new number is 14
Output of third code block; The new number is 15
Output of third code block; The new number is 21
Output of third code block; The new number is 22
Output of third code block; The new number is 23
Output of third code block; The new number is 24
Output of third code block; The new number is 25
Output of third code block; The new number is 31
Output of third code block; The new number is 32
Output of third code block; The new number is 33
Output of third code block; The new number is 34
Output of third code block; The new number is 35
Output of third code block; The new number is 41
Output of third code block; The new number is 42
Output of third code block; The new number is 43
Output of third code block; The new number is 44
Output of third code block; The new number is 45
40

## enumerate

In some cases you might need to use the both the list item and the index of the loop. In such circumstances it is possible to use the enumerate function

In [ ]:
mylist=['one','two','three','four','five']

for index,item in enumerate(mylist):
    print(index,item)

0 one
1 two
2 three
3 four
4 five

# While statements

While loops repeat as long as a certain boolean condition is met e.g.

In [ ]:
count = 0
while count < 5:
    print(count)
    #count += 2  # This is the same as count = count + 1
    count = count + 2 #this will add 2 to count (0) in a loop until count >5, without this line, the code with run forever printing 0's

print('now count is:', count) #this is the first count that made the loop stop

0
2
4
now count is: 6

# Break and continue statements

In some circumstances you may need the option to break out of loop or skip certain elements of a loop. This can be achieved with: 1) break and 2) continue statements:

In [ ]:
# example of a break statement

mylist=['Alice', 'Fred', 'Bob', 'John', 'Steve']

for index,item in enumerate(mylist):
    print(item)
    if item=='John':
        break
        
print('list has stopped at index', index, ' for name ' , item )

Alice
Fred
Bob
John
list has stopped at index 3  for name  John

In [ ]:
# example of use of continue

for index,item in enumerate(mylist):
    if item=='John': # this will cause the loop to skip over entry for 'John'
        continue
    print(item)

Alice
Fred
Bob
Steve

# Looping over Dictionaries

In [ ]:
# create dictionary

mydict={}
mydict['Name']='Dave'
mydict['Age']=23
mydict['job']='Lecturer'
mydict['height']=190
mydict['BMI']=25


for k in mydict.keys(): 
    if k=='height':
        print("The person's height is:", mydict[k])
        break

The person's height is: 190

Note it is so common to loop over keys in a dictionary that a shorthand call is also available (that omits the ```keys``` method)

In [ ]:
for k in mydict: 
    print(k)

Name
Age
job
height
BMI

Using ```items``` it is possible to simultaneously access both key and and value:

In [ ]:
for k,v in mydict.items(): 
    print(k,v)

Name Dave
Age 23
job Lecturer
height 190
BMI 25

# Functions

Functions allow compact structuring of sections of code that are intended to be used more than once in a progam (or indeed multiple programs). 

A function in Python is defined by a ```def``` statement. In psuedocode, the general syntax looks like this:

``` 
def myfunction(arg1,arg2,arg3): # function definition (with optional) input arguments; 
    
    body of code to be repeated
    
    return someval1, someval2 
    ```

Note the colon at the end of the function header, and the use of indentation within the body of the function. Inside the function are lines of code that would otherwise by repeated multiple times in the program. The function then returns (optionally returning output arguments). For simple functions the function can returned in one line e.g.

In [ ]:
# define function
def sum(x,y):
    return x+y # here as the function is simple it can be returned in one line

# apply function

a=5
b=10

print('sum of {} and {} is {}'.format(a,b,sum(a,b)))

sum of 5 and 10 is 15

It is also possible to supply optional input arguments with default values e.g.

In [ ]:
# this function can thus return a sum of 2 or 3 arguments
def sum2(x,y,z=0):
    return x+y+z 

# apply function

a=5
b=10
c=20

print('sum of {} and {} is {}'.format(a,b,sum2(a,b)))
print('sum of {},{} and {} is {}'.format(a,b,c, sum2(a,b,c)))

sum of 5 and 10 is 15
sum of 5,10 and 20 is 35

Or specify which exact optional arguments will be required through use of keywords (referencing the specific argument name in the function call):

In [ ]:
def sumsub(x, y, z1=0, z2=0):
    return x - y + z1 - z2

# apply function

a=5
b=10
c=20
d=30

print(sumsub(12,4))
print(sumsub(42,15,z2=10))
print(sumsub(42,15,z1=20, z2=10))

8
17
37

In all cases the function can take 0 or more input arguments and return 0 or more output arguments. In some cases it is not possible to pre-define the number of arguments. In these cases and arbitrary number of input arguments can be defined using an asterisk:

In [ ]:
def arbitary_sum(*x):
    mysum=0
    for val in x:
        mysum+=val
    return mysum

mylist=[1,2,3,4,5]

print('the sum of values in the list is', arbitary_sum(*mylist))

the sum of values in the list is 15

## Doc strings

When writing code that includes functions it is good practice to document the purpose of the function using a 'doc' string

In [ ]:
def arbitary_sum(*x):
    ''' This function adds and arbitray number of input arguments
    
    input args:
        *x: a list or tuple containing numbers to be summed
    
    returns:
        mysum: result of adding all input arguments
    '''
    
    mysum=0
    for val in x:
        mysum+=val
    return mysum

## Passing by object

In C++ you may have heard the terms 'pass by value' or 'pass by reference' with respect to how arguments are passed to functions. This references how variables are either copied to a new place in memory when they are passed to a function (pass by value) or whether their memory address is passed and shared with the function argument (pass by reference). In the former case, when the argument is changed within the function the original variable remains unchanged. In the latter case, changing the value of the input argument will also change the value of the original variable.

In Python, however, arguments are strictly 'passed by object', what this means is that, what happens to the variable will depend on whether it is mutable or immutable. For immutable types (ints, floats, tuples, strings) the objects are immutable, hence they cannot be changed in the function or out, thus in essence they will be passed 'by value'. 

On the other hand if objects are mutable (lists, dictionaries) then the original values (in the main code body) can and will be changed if the variable is changed in place. But, crucially this will not occur if the arguments are assigned to a new variable inside the body of the code e.g.

In [ ]:
def passing_by_object(names):
    print('In function, input argument is: ',names)
    names = names + ["Emma", "Maria"] 
    print(' After concatenation names contains,', names)
 

mylist=['Alice', 'Fred', 'Bob', 'John', 'Steve']


passing_by_object(mylist)
print('My original list is:', mylist)

In function, input argument is:  ['Alice', 'Fred', 'Bob', 'John', 'Steve']
 After concatenation names contains, ['Alice', 'Fred', 'Bob', 'John', 'Steve', 'Emma', 'Maria']
My original list is: ['Alice', 'Fred', 'Bob', 'John', 'Steve']

However, if the original input argument is edited in place then this will change the change the original variable in the main body of the code

In [ ]:
def passing_by_object2(names):
    print('In function 2, input argument is: ',names)
    names += ["Emma", "Maria"] # here the original variable is changed; 
    print(' After concatenation names contains,', names)


 

mylist=['Alice', 'Fred', 'Bob', 'John', 'Steve']


passing_by_object2(mylist)
print('My original list is:', mylist) # Thus the original list is changed

In function 2, input argument is:  ['Alice', 'Fred', 'Bob', 'John', 'Steve']
 After concatenation names contains, ['Alice', 'Fred', 'Bob', 'John', 'Steve', 'Emma', 'Maria']
My original list is: ['Alice', 'Fred', 'Bob', 'John', 'Steve', 'Emma', 'Maria']

If this behaviour is desired, but perhaps you wish to keep a copy of the original object (during debugging for example), then this can be achieved by making a copy of the original object using the ```copy``` module

In [ ]:
import copy

mylist=['Alice', 'Fred', 'Bob', 'John', 'Steve']


mylist_copy=copy.deepcopy(mylist)

passing_by_object2(mylist)
print('My original list is:', mylist) # The original lists changes
print('My copy list is:', mylist_copy) # But the copy does not

In function 2, input argument is:  ['Alice', 'Fred', 'Bob', 'John', 'Steve']
 After concatenation names contains, ['Alice', 'Fred', 'Bob', 'John', 'Steve', 'Emma', 'Maria']
My original list is: ['Alice', 'Fred', 'Bob', 'John', 'Steve', 'Emma', 'Maria']
My copy list is: ['Alice', 'Fred', 'Bob', 'John', 'Steve']

Note more information will be provided on modules in the next notebook. For more detailed information on the intricacies and implications of this copying behaviour of Python see https://www.python-course.eu/python3_passing_arguments.php

# Exercises - loops and functions:

Ex1  Print First 10 natural numbers using while loop

In [ ]:
# complete the answer to Ex 1 here:
i = 1
while i <= 10:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10

Ex2 Write a program to print the following number pattern using a loop.

1 

1 2 

1 2 3 

1 2 3 4 

1 2 3 4 5

In [ ]:
# complete the answer to Ex 2 here:

# Decide the row count. (above pattern contains 5 rows)
row = 5
# start: 1
# stop: row+1 (range never include stop number in result)
# step: 1
# run loop 5 times
for i in range(1, row + 1, 1):
    # Run inner loop i+1 times
    for j in range(1, i + 1):
        print(j, end=' ')
    # empty line after each row
    print("")

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

Ex3 Find the factorial of a given number

Write a program to use the loop to find the factorial of a given number.

The factorial (symbol: !) means to multiply all whole numbers from the chosen number down to 1.

For example: calculate the factorial of 5

5! = 5 × 4 × 3 × 2 × 1 = 120

Expected output:  120

In [ ]:
# complete the answer to Ex 3 here:
num = 5
factorial = 1
if num < 0:
    print("Factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    # run loop 5 times
    for i in range(1, num + 1):
        # multiply factorial by current number
        factorial = factorial * i
    print("The factorial of", num, "is", factorial)

The factorial of 5 is 120

Ex4 Reverse a given integer number

Given: 76542

Expected output: 24567

In [ ]:
# complete the answer to Ex 4 here:
num = 76542
reverse_number = 0
print("Given Number ", num)
while num > 0:
    reminder = num % 10
    reverse_number = (reverse_number * 10) + reminder
    num = num // 10
print("Revere Number ", reverse_number)

Given Number  76542
Revere Number  24567

Ex 5 Write a loop that prints out all numbers, in the range 0 to 1000 that are divisible by 3 and 5

In [ ]:
# complete the answer to Ex 5 here:
for item in range(1000):
  if (item %3 == 0) and (item %5 == 0):
    print(item)

0
15
30
45
60
75
90
105
120
135
150
165
180
195
210
225
240
255
270
285
300
315
330
345
360
375
390
405
420
435
450
465
480
495
510
525
540
555
570
585
600
615
630
645
660
675
690
705
720
735
750
765
780
795
810
825
840
855
870
885
900
915
930
945
960
975
990

Ex 6. Write a function to multiply all numbers in a list

In [ ]:
# complete the answer to Ex 6 here:
def multiply(x):
  mymult=1
  for val in x:
    mymult*=val
  return mymult

mylist=[2,4,6,8,10]

print("mylist is:", mylist)
print("if i multiply all numbers in my list I get", multiply(mylist))


# define function above lines of code that use it
''' This function multiply and arbitray number of input arguments
    
    input args:
        x: a list or tuple containing numbers to be summed
    
    returns:
        mymult: result of multiplying all input arguments
    '''

# define list and call function
numbers=[2,4,6,8,10]

mylist is: [2, 4, 6, 8, 10]
if i multiply all numbers in my list I get 3840

Ex 7 Write a Python function that checks whether a number (e.g. 71) is prime or not.

In [ ]:
# complete the answer to EX 7 here:
def isprime(num):
    if num> 1:  
        for n in range(2,num):  
            if (num % n) == 0:  
                return False
        return True
    else:
        return False

a=71

print ("{} is a prime number" .format (a, isprime(a)))

71 is a prime number